# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ethaddress',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invitationcode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
